const postTypes = {
  GET_POSTS_START: 'GET_POSTS_START',
  GET_POSTS_SUCCESS: 'GET_POSTS_SUCCESS',
  GET_POSTS_FAIL: 'GET_POSTS_FAIL',

  CREATE_POSTS_START: 'CREATE_POSTS_START',
  CREATE_POSTS_SUCCESS: 'CREATE_POSTS_SUCCESS',
  CREATE_POSTS_FAIL: 'CREATE_POSTS_FAIL',

  LIKE_POST: 'LIKE_POST',
  DISLIKE_POST: 'DISLIKE_POST',
};

export default postTypes;
