const postTypes = {
  GET_POSTS_START: 'GET_POSTS_START',
  GET_POSTS_SUCCESS: 'GET_POSTS_SUCCESS',
  GET_POSTS_FAIL: 'GET_POSTS_FAIL',

  CREATE_POSTS_START: 'CREATE_POSTS_START',
  CREATE_POSTS_SUCCESS: 'CREATE_POSTS_SUCCESS',
  CREATE_POSTS_FAIL: 'CREATE_POSTS_FAIL',

  DELETE_POST_START: 'DELETE_POST_START',
  DELETE_POST_SUCCESS: 'DELETE_POST_SUCCESS',
  DELETE_POST_FAIL: 'DELETE_POST_FAIL',

  UPDATE_POST_START: 'UPDATE_POST_START',
  UPDATE_POST_SUCCESS: 'UPDATE_POST_SUCCESS',
  UPDATE_POST_FAIL: 'UPDATE_POST_FAIL',

  LIKE_POST: 'LIKE_POST',
  DISLIKE_POST: 'DISLIKE_POST',
};

export default postTypes;
